### ISSUE TITLE
Cannot find source file:src/rover_drive.cpp

### ISSUE THREAD

**Issue by yancyxu** [a-mhamdi/rover_ctrl#3]
Hello, I tried to run your excellent project and found the following issue. 
```
CMake Error at CMakeLists.txt:46 (add_executable):
Cannot find source file:

src/rover_drive.cpp
```

May I ask if it is possible to complete the code for this project? 
thank you very much indeed

**Comment by a-mhamdi** [comment]
Please consider the attached _CMakeLists_ file, instead of the one you found in the repo. The latter is a continuity of some work I'm willing to do, but I didn't yet finish. In case you need some _cpp_ codes, you can also get inspired by this project, using ROS (not version 2), available at [https://github.com/bandasaikrishna/Autonomous_Mobile_Robot](https://github.com/bandasaikrishna/Autonomous_Mobile_Robot). 

[CMakeLists.txt](https://github.com/a-mhamdi/rover_ctrl/files/14936769/CMakeLists.txt)

Hope this helps :) Keep me updated
